name: 'Setup Environment'
description: 'Install PNPM, Node and dependencies'

inputs:
  step-name:
    description: 'Installation step name'
    required: false
    default: '⚙️ Install Dependencies'

runs:
  using: 'composite'
  steps:
    - name: 📦 Install PNPM
      uses: pnpm/action-setup@v4

    - name: 🏗️ Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'

    - name: ${{ inputs.step-name }}
      shell: bash
      run: pnpm install --frozen-lockfile
