name: CI/CD Pipeline

on:
  push:
    branches: [main, develop, 'feature/**', 'hotfix/**', 'release/**']
  pull_request:
    branches: [main, develop]

# Cancel current execution for this workflow and branch if a new push is detected
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-integrity:
    name: 👮 Check Lockfile Integrity
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Get Code
        uses: actions/checkout@v4

      - name: 📦 Install PNPM
        uses: pnpm/action-setup@v4

      - name: 🏗️ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: ⚙️ Verify Lockfile Sync
        id: install
        run: pnpm install --frozen-lockfile

      - name: 📢 Failure Notification
        if: failure() && steps.install.outcome == 'failure'
        run: |
          echo "##### 🚨 CRIMINAL ACTIVITY DETECTED ! #####" >> $GITHUB_STEP_SUMMARY
          echo "CI refuses to work with untracked dependencies 😤" >> $GITHUB_STEP_SUMMARY
          echo "Hey ${{ github.actor }}, you modified 'package.json' without updating 'pnpm-lock.yaml' !" >> $GITHUB_STEP_SUMMARY
          echo "👉 Run 'pnpm install' locally and push your updated lockfile plz..." >> $GITHUB_STEP_SUMMARY
          exit 1

  security:
    name: 🛡️ Security Scans
    needs: [check-integrity]
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      contents: read

    steps:
      - name: 📂 Get Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔑 Check Leaked Secrets
        id: gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 📢 Failure Notification
        if: failure() && steps.gitleaks.outcome == 'failure'
        run: |
          echo "##### 🚨 SECURITY BREACH DETECTED ! #####" >> $GITHUB_STEP_SUMMARY
          echo "😱 Are you trying to offer our API Keys to the hackers ?" >> $GITHUB_STEP_SUMMARY
          echo "Hey ${{ github.actor }}, Gitleaks found a secret in your code !" >> $GITHUB_STEP_SUMMARY
          echo "We appreciate your generosity, but please revoke it immediately and remove it from git history." >> $GITHUB_STEP_SUMMARY
          echo "👉 Check the logs in the "🔑 Check Leaked Secrets" step to find the leak..." >> $GITHUB_STEP_SUMMARY
          exit 1

      - name: 📦 Install PNPM
        uses: pnpm/action-setup@v4

      - name: 🏗️ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: ⚙️ Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: 🛡️ PNPM Audit
        run: pnpm audit --audit-level=high

      - name: 🧪 Security Linting
        run: pnpm lint:security:ci

      - name: 🕵️ Snyk Packages Analysis
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          # 🚩 Only blocks if a 'high' vulnerability is found
          command: test
          args: --severity-threshold=high

      - name: 🏗️ Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: javascript-typescript
          queries: security-extended,security-and-quality
          config: |
            paths-ignore:
              - 'src/**/*.spec.ts'
              - 'src/test-setup.ts'

      - name: 🔍 Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4

  quality:
    name: ✨ Quality & Tests
    needs: [check-integrity]
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Get Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Install PNPM
        uses: pnpm/action-setup@v4

      - name: 🏗️ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: ⚙️ Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: 💄 Prettier Formatting
        run: pnpm format:check

      - name: 🧹 ESLint Linting
        run: pnpm lint:ci

      - name: 🔍 HTMLHint Linting
        run: pnpm lint:html

      - name: 🎨 Stylelint SCSS
        run: pnpm lint:scss:ci

      # - name: 🌍 Check i18n Integrity
      #   id: i18n
      #   run: pnpm i18n:lint:ci

      # - name: 📢 Failure Notification
      #   if: failure() && steps.i18n.outcome == 'failure'
      #   run: |
      #     echo "##### 🚨 TRANSLATION POLICE HERE ! #####" >> $GITHUB_STEP_SUMMARY
      #     echo "Hey ${{ github.actor }}, you created new keys but forgot to translate them !" >> $GITHUB_STEP_SUMMARY
      #     echo "Do not leave our users lost in translation. 🗺️" >> $GITHUB_STEP_SUMMARY
      #     echo "👉 Run 'pnpm i18n:extract' locally to generate the missing keys automatically." >> $GITHUB_STEP_SUMMARY
      #     exit 1

      - name: 🧪 Run Vitest Tests & Coverage
        id: vitest
        run: pnpm test:coverage

      - name: 📢 Failure Notification
        if: failure() && steps.vitest.outcome == 'failure'
        run: |
          echo "##### 🚨 CRIMINAL ACTIVITY DETECTED ! #####" >> $GITHUB_STEP_SUMMARY
          echo "❌ Pipeline failed because test coverage is less than 80% !" >> $GITHUB_STEP_SUMMARY
          echo "Hey ${{ github.actor }}, please work harder on your coverage ! 🤣🤣🤣" >> $GITHUB_STEP_SUMMARY
          exit 1

      - name: 🚀 SonarQube Scan
        if: success()
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: 📊 SonarQube Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: 🧱 Build Check
        run: pnpm build --configuration=production

  documentation:
    name: 📚 GitHub Pages Documentation
    needs: [security, quality]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: 📂 Get Code
        uses: actions/checkout@v4

      - name: 📦 Install PNPM
        uses: pnpm/action-setup@v4

      - name: 🏗️ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: ⚙️ Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: 📚 Build Documentation
        run: pnpm doc:ci --base-href /${{ github.event.repository.name }}/

      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.documentation-output

  deploy:
    name: 🎯 Deploy to Production
    needs: [security, quality]
    # 🚩 Temporarily disabled (will never launch)
    # if: github.ref == 'refs/heads/main' && false
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Get Code
        uses: actions/checkout@v4

      - name: 📦 Install PNPM
        uses: pnpm/action-setup@v4

      - name: 🏗️ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: ⚙️ Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: 🧱 Build Project
        run: pnpm build --configuration=production

      - name: 🚀 Sync Files to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

          # Delete from the server the files that are no longer in your code (cleanup)
          ARGS: '-rlgoDazvc -i --delete'

          # ⚠️ Double-check folder name in /dist directory after build (pnpm build)
          SOURCE: 'dist/AngularTemplate/browser/'

          # Avoids sending git configuration files on server
          EXCLUDE: '/node_modules/, /.github/, /.git/'

          # Server IP address
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}

          # Exact location to place code (/home/<your_user>/public_html)
          TARGET: ${{ secrets.TARGET_PATH }}

      - name: 🎯 Deployment
        run: echo "Deployment is underway following security and quality validations..."
