name: 🚧 Toggle Maintenance Mode

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Do you want to enable or disable maintenance ?'
        required: true
        type: choice

        options:
          - '🟢 ENABLE (Switch site to offline mode)'
          - '🔴 DISABLE (Put back site online)'
        default: '🟢 ENABLE (Switch site to offline mode)'

jobs:
  manage-maintenance:
    name: ⚙️ Maintenance Management
    runs-on: ubuntu-latest

    environment: production

    steps:
      # ===== ENABLE =====
      - name: 🚧 Enable Maintenance Mode
        if: ${{ inputs.action == '🟢 ENABLE (Switch site to offline mode)' }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: touch ${{ secrets.TARGET_PATH }}/maintenance.enable

      - name: 📢 Enable Summary
        if: ${{ inputs.action == '🟢 ENABLE (Switch site to offline mode)' }}
        run: |
          echo "##### 🚧 CONSTRUCTION IN PROGRESS ! #####" >> $GITHUB_STEP_SUMMARY
          echo "🟢 The 'maintenance.enable' file has been deployed. The site is serving a static 503 error page." >> $GITHUB_STEP_SUMMARY
          echo "Hey ${{ github.actor }} 👷‍♂️👷👷‍♂️, don't forget to restart the pipeline to bring the site back online when you're finished. 🏗️ " >> $GITHUB_STEP_SUMMARY

      # ===== DISABLE =====
      - name: ✅ Disable Maintenance Mode
        if: ${{ inputs.action == '🔴 DISABLE (Put back site online)' }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: rm -f ${{ secrets.TARGET_PATH }}/maintenance.enable

      - name: 📢 Disable Summary
        if: ${{ inputs.action == '🔴 DISABLE (Put back site online)' }}
        run: |
          echo "##### ✅ CONSTRUCTION SITE COMPLETED ! #####" >> $GITHUB_STEP_SUMMARY
          echo "🚀 The 'maintenance.enable' file has been deleted. Site is online again. 🚀" >> $GITHUB_STEP_SUMMARY
          echo "Good job ${{ github.actor }}. 🥳🥳🥳" >> $GITHUB_STEP_SUMMARY
